version: '3.9'
services:
  api:
    image: teyxos/nest-api
    ports:
      - '3030:3000'
    container_name: api
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - database:/var/lib/postgresql/data/
    container_name: db

volumes:
  database:
